var annotated_dup =
[
    [ "panini", "namespacepanini.html", [
      [ "Braces", "classpanini_1_1_braces.html", "classpanini_1_1_braces" ],
      [ "BracesOptions", "structpanini_1_1_braces_options.html", "structpanini_1_1_braces_options" ],
      [ "CommaList", "classpanini_1_1_comma_list.html", "classpanini_1_1_comma_list" ],
      [ "CommaListOptions", "structpanini_1_1_comma_list_options.html", "structpanini_1_1_comma_list_options" ],
      [ "Command", "classpanini_1_1_command.html", "classpanini_1_1_command" ],
      [ "CommentBlock", "classpanini_1_1_comment_block.html", "classpanini_1_1_comment_block" ],
      [ "CommentLine", "classpanini_1_1_comment_line.html", "classpanini_1_1_comment_line" ],
      [ "CompareWriter", "classpanini_1_1_compare_writer.html", "classpanini_1_1_compare_writer" ],
      [ "CompareWriterConfig", "structpanini_1_1_compare_writer_config.html", "structpanini_1_1_compare_writer_config" ],
      [ "ConfiguredWriter", "classpanini_1_1_configured_writer.html", "classpanini_1_1_configured_writer" ],
      [ "ConsoleWriter", "classpanini_1_1_console_writer.html", "classpanini_1_1_console_writer" ],
      [ "ConsoleWriterConfig", "structpanini_1_1_console_writer_config.html", null ],
      [ "DebugWriter", "classpanini_1_1_debug_writer.html", "classpanini_1_1_debug_writer" ],
      [ "DebugWriterConfig", "structpanini_1_1_debug_writer_config.html", "structpanini_1_1_debug_writer_config" ],
      [ "FeatureFlag", "classpanini_1_1_feature_flag.html", "classpanini_1_1_feature_flag" ],
      [ "FileWriter", "classpanini_1_1_file_writer.html", "classpanini_1_1_file_writer" ],
      [ "FileWriterConfig", "structpanini_1_1_file_writer_config.html", "structpanini_1_1_file_writer_config" ],
      [ "Include", "classpanini_1_1_include.html", "classpanini_1_1_include" ],
      [ "IncludeBlock", "classpanini_1_1_include_block.html", "classpanini_1_1_include_block" ],
      [ "IncludeEntry", "structpanini_1_1_include_entry.html", "structpanini_1_1_include_entry" ],
      [ "IncludeSet", "classpanini_1_1_include_set.html", "classpanini_1_1_include_set" ],
      [ "IndentPop", "structpanini_1_1_indent_pop.html", null ],
      [ "IndentPush", "structpanini_1_1_indent_push.html", null ],
      [ "Label", "classpanini_1_1_label.html", "classpanini_1_1_label" ],
      [ "NextLine", "structpanini_1_1_next_line.html", null ],
      [ "Scope", "classpanini_1_1_scope.html", "classpanini_1_1_scope" ],
      [ "ScopeOptions", "structpanini_1_1_scope_options.html", "structpanini_1_1_scope_options" ],
      [ "StringWriter", "classpanini_1_1_string_writer.html", "classpanini_1_1_string_writer" ],
      [ "StringWriterConfig", "structpanini_1_1_string_writer_config.html", null ],
      [ "Writer", "classpanini_1_1_writer.html", "classpanini_1_1_writer" ],
      [ "WriterConfig", "structpanini_1_1_writer_config.html", "structpanini_1_1_writer_config" ]
    ] ]
];